# Generated by Django 6.0.5 on 2026-05-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FellowshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('theme', models.CharField(max_length=255)),
                ('bible_verse', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('theme_description', models.TextField()),
                ('speaker', models.CharField(max_length=255)),
                ('speaker_pic', models.CharField(max_length=255)),
                ('speaker_status', models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=20)),
                ('mc', models.CharField(max_length=255)),
                ('musician', models.CharField(max_length=255)),
                ('worship_team_pic', models.CharField(max_length=255)),
                ('worship_team_status', models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=20)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
